import React from "react"

export interface menu {
  Items?: menu[]
  title?: string
  icon?: JSX.Element
  type?: string
  selected?: boolean
  active?: boolean
  path?: string
  children?: menu[]
  badge?: string
  badgetxt?: string
}



export const MENUITEMS: menu[] = [
  {
    Items: [
      {
        title: "Dashboards",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}dashboard/dashboard01`,
            type: "link",
            active: false,
            selected: false,
            title: "Dashboard 01",
          }
        ],
      },
    ],
  },
  // {
  //   Items: [
  //     {
  //       title: "Apps",
  //       icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Chat",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/chat/chat`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Chat",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/chat/chat02`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Chat 02",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/chat/chat03`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Chat 03",
  //             },
  //           ],
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Contact",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/contact/contactlist`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Contact list",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/contact/contactlist02`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Contact list 02",
  //             },
  //           ],
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "File Manager",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/filemanager/filemanager`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "File Manager",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/filemanager/filemanager02`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "File Manager 02",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/filemanager/filedetails`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "File Details",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/filemanager/fileattachments`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "File Attachments",
  //             },
  //           ],
  //         },
          
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Todo List",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/todolist/todolist`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Todo List",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/todolist/todolist02`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Todo List 02",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/todolist/todolist03`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Todo List 03",
  //             },
  //           ],
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "User List",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/userlist/userlist01`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "User List 01",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/userlist/userlist02`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "User List 02",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/userlist/userlist03`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "User List 03",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/userlist/userlist04`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "User List 04",
  //             },
  //           ],
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Maps",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}Apps/Maps/SimpleMaps`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Simple Maps",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}apps/maps/leafletmaps`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Leaflet Maps",
  //             },
  //           ],
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/calendar`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Calendar",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/imagecrop`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Image Crop",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/pagesessiontimeout`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Page Sessiontimeout",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/notifications`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Notifications",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/sweetalerts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Sweet Alerts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/rangeslider`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Range Slider",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/counters`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Counters",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/loaders`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Loaders",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/timeline`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Time Line",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apps/rating`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Rating",
  //         },
  //       ],
  //     }
  //   ]
  // },
  // {
  //   Items: [
  //     {
  //       title: "Widgets",
  //       icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}widgets/widgets`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Widgets",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}widgets/chartwidgets`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Chart Widgets",
  //         },

  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Forms",
  //       icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelements`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Elements",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/advancedforms`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Advanced Forms",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formwizard`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Wizard",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formedit`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Edit",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formelementsizes`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Element Sizes",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}forms/formtreeview`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Treeview",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Charts",
  //       icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path><path d="M22 12A10 10 0 0 0 12 2v10z"></path></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Apex Charts",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexcharts/area`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Area",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexcharts/bar`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Bar",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexcharts/column`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Column",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexcharts/line`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Line",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexcharts/mixed`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Mixed",
  //             },
  //           ],
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}charts/chartjs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Chartjs Charts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}charts/echart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Echart Charts",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Tables",
  //       icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}tables/defaulttable`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Default Table",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}tables/datatable`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Data Table",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Elements",
  //       icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/accordion`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Accordion",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/alerts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Alerts",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/avatars`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Avatars",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/badges`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Badges",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/breadcrumb`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Breadcrumb",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/buttons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Buttons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/cards`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Cards",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/cardimages`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Card Images",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/carousel`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Carousel",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/dropdown`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Dropdown",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/footers`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Footers",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/headers`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Headers",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/list`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "list",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/mediaobject`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Media Object",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/modal`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Modal",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/navigation`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Navigation",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/pagination`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Pagination",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/panel`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Panel",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/popover`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Popover",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/progress`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Progress",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/tabs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tabs",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/tags`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tags",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}elements/tooltips`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tooltips",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Icons",
  //       icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"></path></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/fontawesome`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Font Awesome",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/materialdesignicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Material Design Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/simplelineicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Simple Line Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/feathericons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Feather Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/ionicicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Ionic Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/flagicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Flag Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/pe7icons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Pe7 Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/themifyicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Themify Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/typiconsicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tyicons Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/weathericons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Weather Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/materialicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Material Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/bootstrap5svgicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Bootstrap5 SVG Icons",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Pages",
  //       icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Profile",
  //           children: [
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Profile 01",
  //               path: `${import.meta.env.BASE_URL}pages/profile/profile01`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Profile 02",
  //               path: `${import.meta.env.BASE_URL}pages/profile/profile02`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Profile 03",
  //               path: `${import.meta.env.BASE_URL}pages/profile/profile03`,
  //             },
  //           ],
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/aboutus`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "About Us",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/editprofile`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Edit Profile",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/settings`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Settings",
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Email",
  //           children: [
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Email Compose",
  //               path: `${import.meta.env.BASE_URL}pages/email/emailcompose`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Email Inbox",
  //               path: `${import.meta.env.BASE_URL}pages/email/emailinbox`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Email Read",
  //               path: `${import.meta.env.BASE_URL}pages/email/emailread`,
  //             },
  //           ],
  //         },
  //         {

  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Pricing",
  //           children: [
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Pricing 01",
  //               path: `${import.meta.env.BASE_URL}pages/pricing/pricing01`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "pricing 02",
  //               path: `${import.meta.env.BASE_URL}pages/pricing/pricing02`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "pricing 03",
  //               path: `${import.meta.env.BASE_URL}pages/pricing/pricing03`,
  //             },
  //           ],
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Invoice",
  //           children: [
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Invoice list",
  //               path: `${import.meta.env.BASE_URL}pages/invoice/invoicelist`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Invoice 01",
  //               path: `${import.meta.env.BASE_URL}pages/invoice/invoice01`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Invoice 02",
  //               path: `${import.meta.env.BASE_URL}pages/invoice/invoice02`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Invoice 03",
  //               path: `${import.meta.env.BASE_URL}pages/invoice/invoice03`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Add Invoice",
  //               path: `${import.meta.env.BASE_URL}pages/invoice/addinvoice`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Edit Invoice",
  //               path: `${import.meta.env.BASE_URL}pages/invoice/editinvoice`,
  //             },
  //           ],
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Blog",
  //           children: [
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog 01",
  //               path: `${import.meta.env.BASE_URL}pages/blog/blog01`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog 02",
  //               path: `${import.meta.env.BASE_URL}pages/blog/blog02`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog 03",
  //               path: `${import.meta.env.BASE_URL}pages/blog/blog03`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog Styles",
  //               path: `${import.meta.env.BASE_URL}pages/blog/blogstyles`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog Post",
  //               path: `${import.meta.env.BASE_URL}pages/blog/blogpost`,
  //             },
  //           ],
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "E-commerce",
  //           children: [
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Products",
  //               path: `${import.meta.env.BASE_URL}pages/ecommerce/products`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Product Details",
  //               path: `${import.meta.env.BASE_URL}pages/ecommerce/productdetails`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Shopping Cart",
  //               path: `${import.meta.env.BASE_URL}pages/ecommerce/shoppingcart`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Checkout",
  //               path: `${import.meta.env.BASE_URL}pages/ecommerce/checkout`,
  //             },
  //             {
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Wishlist",
  //               path: `${import.meta.env.BASE_URL}pages/ecommerce/wishlist`,
  //             },
  //           ],
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/gallery`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Gallery",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/faqs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "FAQS",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/terms`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Terms",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/emptypage`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Empty Page",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/switcher`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Switcher",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/search`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Search",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Submenus",
  //       icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}#`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Level-1",
  //         },
  //         {
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           title: "Level-2",

  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}#`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Level-2.1",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}#`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Level-2.2",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}#`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Level-2.3",
  //             },

  //           ],
  //         },

  //       ],
  //     },
  //   ],
  // },
  {
    Items: [
      {
        title: "Usuarios",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}users/users`,
            type: "link",
            active: false,
            selected: false,
            title: "Usuarios",
          },
          {
            path: `${import.meta.env.BASE_URL}users/roles`,
            type: "link",
            active: false,
            selected: false,
            title: "Roles",
          },
          {
            path: `${import.meta.env.BASE_URL}users/permissions`,
            type: "link",
            active: false,
            selected: false,
            title: "Permisos",
          },                    
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Inventario",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}users/products`,
            type: "link",
            active: false,
            selected: false,
            title: "Productos",
          },
          {
            path: `${import.meta.env.BASE_URL}users/promotions`,
            type: "link",
            active: false,
            selected: false,
            title: "Promociones",
          },
          {
            path: `${import.meta.env.BASE_URL}users/services`,
            type: "link",
            active: false,
            selected: false,
            title: "Servicios",
          },                    
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Compras",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><path d="M0 0h24v24H0z" fill="none"/><path d="M7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zM1 2v2h2l3.6 7.59-1.35 2.45c-.16.28-.25.61-.25.96 0 1.1.9 2 2 2h12v-2H7.42c-.14 0-.25-.11-.25-.25l.03-.12.9-1.63h7.45c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.08-.14.12-.31.12-.48 0-.55-.45-1-1-1H5.21l-.94-2H1zm16 16c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z"/></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}users/sales`,
            type: "link",
            active: false,
            selected: false,
            title: "Cotización",
          },
          {
            path: `${import.meta.env.BASE_URL}users/promotionszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Orden de Compra",
          },
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Guia de Remisión",
          },
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Comprobante F|B|NCS",
          },                                
        ],
      },
    ],
  },  
  {
    Items: [
      {
        title: "Ventas",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><g><rect fill="none" height="24" width="24"/><path d="M17,2H7C5.9,2,5,2.9,5,4v2c0,1.1,0.9,2,2,2h10c1.1,0,2-0.9,2-2V4C19,2.9,18.1,2,17,2z M17,6H7V4h10V6z M20,22H4 c-1.1,0-2-0.9-2-2v-1h20v1C22,21.1,21.1,22,20,22z M18.53,10.19C18.21,9.47,17.49,9,16.7,9H7.3c-0.79,0-1.51,0.47-1.83,1.19L2,18 h20L18.53,10.19z M9.5,16h-1C8.22,16,8,15.78,8,15.5C8,15.22,8.22,15,8.5,15h1c0.28,0,0.5,0.22,0.5,0.5C10,15.78,9.78,16,9.5,16z M9.5,14h-1C8.22,14,8,13.78,8,13.5C8,13.22,8.22,13,8.5,13h1c0.28,0,0.5,0.22,0.5,0.5C10,13.78,9.78,14,9.5,14z M9.5,12h-1 C8.22,12,8,11.78,8,11.5C8,11.22,8.22,11,8.5,11h1c0.28,0,0.5,0.22,0.5,0.5C10,11.78,9.78,12,9.5,12z M12.5,16h-1 c-0.28,0-0.5-0.22-0.5-0.5c0-0.28,0.22-0.5,0.5-0.5h1c0.28,0,0.5,0.22,0.5,0.5C13,15.78,12.78,16,12.5,16z M12.5,14h-1 c-0.28,0-0.5-0.22-0.5-0.5c0-0.28,0.22-0.5,0.5-0.5h1c0.28,0,0.5,0.22,0.5,0.5C13,13.78,12.78,14,12.5,14z M12.5,12h-1 c-0.28,0-0.5-0.22-0.5-0.5c0-0.28,0.22-0.5,0.5-0.5h1c0.28,0,0.5,0.22,0.5,0.5C13,11.78,12.78,12,12.5,12z M15.5,16h-1 c-0.28,0-0.5-0.22-0.5-0.5c0-0.28,0.22-0.5,0.5-0.5h1c0.28,0,0.5,0.22,0.5,0.5C16,15.78,15.78,16,15.5,16z M15.5,14h-1 c-0.28,0-0.5-0.22-0.5-0.5c0-0.28,0.22-0.5,0.5-0.5h1c0.28,0,0.5,0.22,0.5,0.5C16,13.78,15.78,14,15.5,14z M15.5,12h-1 c-0.28,0-0.5-0.22-0.5-0.5c0-0.28,0.22-0.5,0.5-0.5h1c0.28,0,0.5,0.22,0.5,0.5C16,11.78,15.78,12,15.5,12z"/></g></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}users/sales`,
            type: "link",
            active: false,
            selected: false,
            title: "Cotización",
          },
          {
            path: `${import.meta.env.BASE_URL}users/promotionszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Orden de Compra",
          },
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Guia de Remisión",
          },
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Comprobante F|B|NCS",
          },                                
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Empresas",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><g><path d="M0,0h24v24H0V0z" fill="none"/><path d="M12,7V3H2v18h20V7H12z M6,19H4v-2h2V19z M6,15H4v-2h2V15z M6,11H4V9h2V11z M6,7H4V5h2V7z M10,19H8v-2h2V19z M10,15H8v-2h2 V15z M10,11H8V9h2V11z M10,7H8V5h2V7z M20,19h-8v-2h2v-2h-2v-2h2v-2h-2V9h8V19z M18,11h-2v2h2V11z M18,15h-2v2h2V15z"/></g></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}users/company`,
            type: "link",
            active: false,
            selected: false,
            title: "Empresas",
          },                                                        
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Reportes",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm2 16H8v-2h8v2zm0-4H8v-2h8v2zm-3-5V3.5L18.5 9H13z"/></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}report/invoice`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Factura",
          },
          {
            path: `${import.meta.env.BASE_URL}report/administrative`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Administrativo",
          },
          {
            path: `${import.meta.env.BASE_URL}report/statistical`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Estadístico",
          },                                                  
          {
            path: `${import.meta.env.BASE_URL}report/accumulated/day`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Acumulado por Día",
          },
          {
            path: `${import.meta.env.BASE_URL}report/sale`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte de Venta",
          },
          {
            path: `${import.meta.env.BASE_URL}report/effective/control`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Control Efectivo",
          },
          {
            path: `${import.meta.env.BASE_URL}report/bank`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte de Bancos",
          },
          {
            path: `${import.meta.env.BASE_URL}report/pretty/cash`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Caja Chica",
          },  
          {
            path: `${import.meta.env.BASE_URL}report/collection`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Cobranzas",
          },
          {
            path: `${import.meta.env.BASE_URL}report/profitability`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Rentabilidad",
          },
          {
            path: `${import.meta.env.BASE_URL}report/sale/note`,
            type: "link",
            active: false,
            selected: false,
            title: "Reporte Nota de Venta",
          },                                                                        
        ],
      },
    ],
  },        
  {
    Items: [
      {
        title: "Configuración",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><g><path d="M0,0h24v24H0V0z" fill="none"/><path d="M19.14,12.94c0.04-0.3,0.06-0.61,0.06-0.94c0-0.32-0.02-0.64-0.07-0.94l2.03-1.58c0.18-0.14,0.23-0.41,0.12-0.61 l-1.92-3.32c-0.12-0.22-0.37-0.29-0.59-0.22l-2.39,0.96c-0.5-0.38-1.03-0.7-1.62-0.94L14.4,2.81c-0.04-0.24-0.24-0.41-0.48-0.41 h-3.84c-0.24,0-0.43,0.17-0.47,0.41L9.25,5.35C8.66,5.59,8.12,5.92,7.63,6.29L5.24,5.33c-0.22-0.08-0.47,0-0.59,0.22L2.74,8.87 C2.62,9.08,2.66,9.34,2.86,9.48l2.03,1.58C4.84,11.36,4.8,11.69,4.8,12s0.02,0.64,0.07,0.94l-2.03,1.58 c-0.18,0.14-0.23,0.41-0.12,0.61l1.92,3.32c0.12,0.22,0.37,0.29,0.59,0.22l2.39-0.96c0.5,0.38,1.03,0.7,1.62,0.94l0.36,2.54 c0.05,0.24,0.24,0.41,0.48,0.41h3.84c0.24,0,0.44-0.17,0.47-0.41l0.36-2.54c0.59-0.24,1.13-0.56,1.62-0.94l2.39,0.96 c0.22,0.08,0.47,0,0.59-0.22l1.92-3.32c0.12-0.22,0.07-0.47-0.12-0.61L19.14,12.94z M12,15.6c-1.98,0-3.6-1.62-3.6-3.6 s1.62-3.6,3.6-3.6s3.6,1.62,3.6,3.6S13.98,15.6,12,15.6z"/></g></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}users/config`,
            type: "link",
            active: false,
            selected: false,
            title: "Monedas",
          },
          {
            path: `${import.meta.env.BASE_URL}users/promotionszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Almacen",
          },
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Moneda",
          },
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Método de Pago",
          },
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Local",
          },  
          {
            path: `${import.meta.env.BASE_URL}users/serviceszz`,
            type: "link",
            active: false,
            selected: false,
            title: "Vehículo",
          },                                                         
        ],
      },
    ],
  },        
  // {
  //   Items: [
  //     {
  //       title: "Error Pages",
  //       icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}errorpages/error400`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "400",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}errorpages/error401`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "401",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}errorpages/error403`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "403",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}errorpages/error404`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "404",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}errorpages/error500`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "500",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}errorpages/error503`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "503",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Items: [
  //     {
  //       title: "Utilities",
  //       icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line></svg>,
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/color`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Color",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/flexitems`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Flex Items",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/height`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Height",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/border`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Border",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/display`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Display",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/margin`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Margin",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/padding`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Padding",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/typography`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Typography",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}utilities/width`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Width",
  //         },
  //       ],
  //     },
  //   ],
  // },
];
